volumes:
  demo1:

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: openjdk
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/dbtest'

  postgres:
    image: postgres:16-alpine
    container_name: postgres16
    environment:
      - POSTGRES_DB=dbtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - demo1:/lib/postgres/data
    ports:
      - 5432


