
services:
  app:
    image: emjas/demoexample1
    volumes:
      - ./:/app
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dbtest
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
  db:
    image: postgres:16
    container_name: postgres16
    environment:
      - POSTGRES_DB=dbtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./:/app
    ports:
      - 5432




